#!/bin/bash

a=512
r=251
for i in {1..15}
do
    for j in {1..3}
    do
        ../bin/spgrid $a 16 $r -cl10000 -s | ../bin/dikh ../results/$0.$a.$j
        r=$(expr 1 + $r)
    done
    a=$(expr 2 \* $a)
done

